DELIMITER //

CREATE PROCEDURE `REGISTRO` (IN PCEDULA INT , IN PNOMBRE VARCHAR(50) , IN PAPELLIDO VARCHAR(50), IN PUSUARIO VARCHAR(50),
							 IN PCONTRASENIA VARCHAR(50), IN PTELEFONO VARCHAR(50),IN PCORREO VARCHAR(50), IN PTIPOPERSONA INT)
BEGIN

INSERT INTO usuario (NomUsuario, Contrasenia, permisos) VALUES (PUSUARIO, MD5(PCONTRASENIA), 2);

INSERT INTO persona (idPersona, Usuario_idUsuario, Tipo_de_Persona_idTipo_de_Persona, Nombre, Apellido)
VALUES 				(PCEDULA, LAST_INSERT_ID(), PTIPOPERSONA, PNOMBRE, PAPELLIDO);

INSERT INTO telefono (Persona_idPersona, Telefono) VALUES (PCEDULA, PTELEFONO);

INSERT INTO correo (Persona_idPersona, Correo) VALUES (PCEDULA, PCORREO);

END //


CALL REGISTRO (113790395,'Adrián','Soto','asoto','1234','83262011','sotoadrian4@gmail.com',1);